version: "3.9"
networks:
  default:
    external:
      name: local-net
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: samaya
      POSTGRES_PASSWORD: samaya
    ports:
      - "5432:5432"
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/testrails
    ports:
      - "3000:3000"
    depends_on:
      - db